services:
  - type: web
    name: fastapi-app
    env: python
    region: oregon
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    runtime: docker
    dockerfilePath: ./Dockerfile
